{
 "title": "AppGate Dashboard All Collectives",
 "tags": [
  "appgate",
  "dashboard",
  "provisioned"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Appliance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CTL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(controller_count{})", "legendFormat": "controller" }
   ]
  },
  {
   "title": "offline",
   "type": "stat",
   "description": "controllers",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appliance_status_online{online=\"false\",role_controller=\"true\"})"
    }
   ]
  },
  {
   "title": "Appl",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(appliance_count{})", "legendFormat": "Appliances" }
   ]
  },
  {
   "title": "Off",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(appliance_status_online{online=\"false\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Deact",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appliance_activated{appliance_activated=\"false\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 10, "y": 1 } },
  {
   "title": "Conkolla Health",
   "type": "table-old",
   "description": "Conkolla not 200 resp code",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count(connection_roundtrip{http_response_code!~\"2.*\"}) by (http_response_code)",
     "legendFormat": "{{http_response_code}}"
    },
    {
     "expr": "absent(connection_roundtrip{http_response_code!~\"2.*\"})-2",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_distinct_user_count{})"
    }
   ]
  },
  {
   "title": "Sys bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(quantile_over_time(0.95, appliance_network_tx_bps[2m])) + sum(quantile_over_time(0.95, appliance_network_rx_bps[2m]))"
    }
   ]
  },
  {
   "title": "Sites",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " count(count by (site_id) (appliance_status_online) )"
    },
    { "expr": "app" }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(gateway_nr_sessions{})", "legendFormat": "GW sessions" },
    {
     "expr": "sum(session_distinct_user_count{})",
     "legendFormat": "distinct users"
    }
   ]
  },
  {
   "title": "GW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(gateway_count{})", "legendFormat": "gateways" }
   ]
  },
  {
   "title": "offline",
   "type": "stat",
   "description": "gateways",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appliance_status_online{online=\"false\",role_gateway=\"true\"})  "
    }
   ]
  },
  {
   "title": "AppGate Version",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "count(appgate:appliance_version_count:labels_to_table{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IOT ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(iotconnector_count{})", "legendFormat": "IOTcon" }
   ]
  },
  {
   "title": "offline",
   "type": "stat",
   "description": "connectors",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appliance_status_online{online=\"false\",role_iotconnector=\"true\"})"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "role_status_appliance{health=\"busy\"} +1",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "role_status_appliance{health=\"warning\"} +4",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "role_status_appliance{health=\"error\"} +12",
     "legendFormat": "{{appliance_name}} "
    },
    {
     "expr": "appliance_status_online{online=\"false\"} + 8",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "LOG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(logserver_count{})", "legendFormat": "logserver" }
   ]
  },
  {
   "title": "offline",
   "type": "stat",
   "description": "logservers",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(appliance_status_online{online=\"false\",role_logserver=\"true\"})"
    }
   ]
  },
  {
   "title": "Dropped packages 5 min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(appliance_network_dropin{}[5m]) ",
     "legendFormat": "IN {{appliance_name}} {{busiest_nic}}"
    },
    {
     "expr": "- increase(appliance_network_dropout{}[5m]) ",
     "legendFormat": "OUT {{appliance_name}} {{busiest_nic}}"
    }
   ]
  }
 ]
}